### PR TITLE
Updates to the /working_groups resource #167

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by chrisguindon** [comment]
@autumnfound The list of WG should be complete:
https://github.com/EclipseFdn/react-eclipsefdn-members/blob/4db29dcd75ab6f43159b5f0917b9c40fa9f7c43b/src/main/resources/working_groups.json

A few things to note:

- OpenHW Group is included in the JSON but we don't want to include them in the Enrollment Form.
- OpenHW Group has an extra property under resources called membership that the other entries don't have.

**Comment by autumnfound** [comment]
@linkfang we will need to integrate this into the front end as well. My advice would be to use a sample of the output from the openapi yaml as a starting point, and make the required changes in a secondary branch. Once those are ready, I can squash them and pull them into this branch. Does that work for you?

**Comment by linkfang** [comment]
Hi @autumnfound , the changes are done. It's a small change. Here is the commit:
https://github.com/linkfang/react-eclipsefdn-members/commit/a6f6f32da913968784df2120ecabe00718636f4c

I tested, React works well with the new wg data structure and the info can be saved into the db.
But I will get a 500 response on the /complete request. (Everything is saved into db without error, just the final submit will fail)

**Comment by autumnfound** [comment]
> Hi @autumnfound , the changes are done. It's a small change. Here is the commit:
> [linkfang@a6f6f32](https://github.com/linkfang/react-eclipsefdn-members/commit/a6f6f32da913968784df2120ecabe00718636f4c)
> 
> I tested, React works well with the new wg data structure and the info can be saved into the db.
> But I will get a 500 response on the /complete request. (Everything is saved into db without error, just the final submit will fail)

That might be because of bad setup for the mailer. If you don't have good smtp set up, it would probably blow up. We don't really want it sending in dev anyways so for now it doesn't really matter, as we didn't change anything with complete

**Comment by autumnfound** [comment]
I put us all as reviewers, with the assumption we will look over code that is not our own. If we want to test this we will need to pull this into our environment as it wont be evident on preview

**Comment by chrisguindon** [comment]
Working Group fees would not be calculated for organizations in the enrollment form. However, it's important that we include a link to the charter of each working group to allow users to view the fees while submitting the form.

I believe we already implemented this but adding this to make sure.

**Pull request merged**
