### PR TITLE
Add SSL support via generated certs

### PR DESCRIPTION
**Pull request by autumnfound**

### CODE REVIEW

**Comment by autumnfound** [comment]
@chrisguindon could you test this? You'll need to do a full build, but this should enable SSL and disable HTTP on the REM app

**Review by fredg02 — APPROVED** [review]
Nothing looks plain wrong to me. ;) Since I have no experience with Quarkus and adding SSL support to it I can't comment on the syntactic or logic correctness.

**Comment by autumnfound** [comment]
> Nothing looks plain wrong to me. ;) Since I have no experience with Quarkus and adding SSL support to it I can't comment on the syntactic or logic correctness.

For sure! Its pretty new to me too. The method to the madness is that you mount your cert and key as secrets, mount them in your volume, and link them through the env vars. Then quarkus will take care of retrieving and using that cert for requests.

**Comment by chrisguindon** [comment]
We can wait to deploy this when @mbarbero is back.

**Comment by mbarbero** [comment]
What is the intent with this PR? What kind of threat do you try to mitigate or what kind of issue do you try to solve?

**Comment by autumnfound** [comment]
> What is the intent with this PR? What kind of threat do you try to mitigate or what kind of issue do you try to solve?

The goal was to improve security through explicit SSL/https support rather than standard HTTP. Is this something that won't do what we think it does?

**Comment by chrisguindon** [comment]
@mbarbero end-to-end encryption.

**Comment by mbarbero** [comment]
> @mbarbero end-to-end encryption.

what are the ends?

**Comment by chrisguindon** [comment]
> > @mbarbero end-to-end encryption.
> 
> what are the ends?

As far as I understand, the services is running on HTTP on okd. I don't think it's a requirement for this project. However, I have asked Martin to look at this so that we know how to do it for the Foundation DB.

Are you trying to tell us we don't need to services that store PII information on https in our old cluster?

**Comment by mbarbero** [comment]
I'm trying to make you elaborate about your goals here. Adding TLS in front of the service does not provide magical e2e encryption if you don't understand what are the ends. A false sense of security would be worse than a good understanding of the actual threats.

**Comment by chrisguindon** [comment]
@mbarbero I don't understand your point here. Can you explain why we don't need it on the OKD cluster.

I am starting to wrap my head around this whole thing. I do understand, that this level is encryption will only encrypt the data from within our network.  When dealing with PII, I do think we should do what we can to protect it. 

What I don't understand yet, and what I was hoping to get from this exercise is a better understanding of the work needed for getting this done.

Can you please explain what are your reservation about this? 

It's too much work for what we get back from it or it's we simply because don't need to have an encrypted connection on okd since there is no way for an attacker to create a man-in-the-middle attack in the first place for example?

**Comment by chrisguindon** [comment]
@mbarbero To add to this. I was planning to require that we run all our APIs on HTTPS in our cluster. My reasoning was, if we can figure how to configure it without too much extra work, it would be worth it.

However, I am open to change this plan of mind if you think it's not nessasery.

**Comment by mbarbero** [comment]
> @mbarbero I don't understand your point here. Can you explain why we don't need it on the OKD cluster?

I did not say that. My point is to challenge what you want to achieve with this patch. Of course, TLS provides encryption and it's better to encrypt stuff, especially PII.

But this will run within an environment with various proxies that may terminate TLS at various locations. I want to understand what are the _ends_ that will talk to this service (public internet, other services in the cluster only, other services behind our firewall...) and what are the threats we want to mitigate. 

From there, we can design the best solution at the best cost.

**Comment by chrisguindon** [comment]
Let's hold off for now. Converting to a draft. 

Mika and I are planning to discuss this in order to determine the next steps.

**Pull request closed without merging**
